### ISSUE TITLE
the plugin is not working correctly

### ISSUE THREAD

**Issue by MichaelKozlovOfficial** [Bram1903/MinecraftPlayerCrasher#17]
I no longer use this plugin, because in the last of my tests of 10 players crashed only 2, the rest failed, from this I conclude that the plugin is useless. perhaps someday I will make a fork of this plugin and fix this problem. 

The author is not trying to fix, he tests only on himself, on myself and I can crash, but it is necessary to test on live people

the server is running on 1.12.2 and 90% of 1.12.2 were playing at the time

**Comment by MichaelKozlovOfficial** [comment]
No one would intentionally defend themselves against “crash”. Did all the players defend themselves? Are you kidding me?

**Comment by Bram1903** [comment]
Hello,

Look, I understand you're frustrated, but this is starting to feel more like noise than constructive feedback. I work on this project in my spare time, and while I do fix major issues, it’s not always at the top of my list. If you check the closed issues, you’ll see I’ve been addressing problems, so claiming I’m not trying is simply not true.

You bring up forking the project—by all means, go ahead if you think you can fix it. That’s how open-source works. Ever heard of contributing through pull requests? I’m sure it’d be more productive than leaving comments like this.

Also, you're running an outdated 1.12.2 server, which hardly anyone uses anymore. Maybe the issue lies there, especially since you're also facing problems with other plugins like PacketEvents. It seems like the common denominator here is your setup, not my plugin.

I’m happy to fix legitimate issues, but this persistent complaining is tiresome and unhelpful.

Bram

**Comment by MichaelKozlovOfficial** [comment]
no problems with packetevents and I wrote the criticism, if you're afraid of it, that's your problem and you can block me.

**Comment by MichaelKozlovOfficial** [comment]
https://github.com/Bram1903/MinecraftPlayerCrasher/issues/14 
Why did he even write this? Because he's probably experienced the same problem.

**Comment by MichaelKozlovOfficial** [comment]
thanks for closing the issues, that's it, I won't reply to you. lazy authors

**Comment by Bram1903** [comment]
> #14 Why did he even write this? Because he's probably experienced the same problem.

The issue you mentioned, where players were getting kicked due to network problems if they couldn’t be crashed, has already been fixed. Yes, there are clients out there that can bypass this crasher, and that's to be expected. However, a network issue that arises because of that, obviously isn't. Thus I fixed that issue.

> Thanks for closing the issues, that’s it, I won’t reply to you. Lazy authors.

Lazy? I'm a university student juggling my studies, a job, and maintaining multiple open-source projects. Calling someone lazy when you don’t know their workload or contributions is disrespectful. Maybe show some of your own work before criticizing others who are volunteering their time.

Bram

**Comment by MichaelKozlovOfficial** [comment]
> > #14 Why did he even write this? Because he's probably experienced the same problem.
> 
> The issue you mentioned, where players were getting kicked due to network problems if they couldn’t be crashed, has already been fixed. Yes, there are clients out there that can bypass this crasher, and that's to be expected. However, a network issue that arises because of that obviously isn't. Thus I fixed that issue.
> 
> > Thanks for closing the issues, that’s it, I won’t reply to you. Lazy authors.
> 
> Lazy? I'm a university student juggling my studies, a job, and maintaining multiple open-source projects. Calling someone lazy when you don’t know their workload or contributions is disrespectful. Maybe show some of your own work before criticizing others who are volunteering their time.
> 
> Bram

There is no point in arguing, if when the plugin becomes popular and users every day will write to you that failed to crash , maybe then you will believe it

**Comment by MichaelKozlovOfficial** [comment]
I noticed that when you kick players if you can't crash and then they re-login after kick, some of them can crash now.
