### ISSUE TITLE
Update PacketEvents

### ISSUE THREAD

**Issue by F3F5** [Bram1903/MinecraftPlayerCrasher#4]
[packetevents] com.deathmotion.playercrasher.shaded.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 193615 to a PacketType constant. Bound: SERVER, Connection state: PLAY, Server version: 1.12.2
[packetevents] com.deathmotion.playercrasher.shaded.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 193615 to a PacketType constant. Bound: SERVER, Connection state: PLAY, Server version: 1.12.2
[packetevents] Disconnected SuperKanalYT due to invalid packet!

[packetevents] Unable to grab ViaVersion client version for player!
[packetevents] Unable to grab ViaVersion client version for player!
 Saving players

**Comment by Bram1903** [comment]
Hello @F3F5, 

Thanks for creating this issue, but could you perhaps provide more context? Does the error occur often or always, or only in certain scenarios, etc? 

Kind regards,
Bram

**Comment by F3F5** [comment]
![Screenshot_1](https://github.com/Bram1903/MinecraftPlayerCrasher/assets/108226177/76e2d1f3-5856-4e04-8563-66d3be5b8097)

Yes, always error 
And always this [packetevents] Unable to grab ViaVersion client version for player! when stopping server

**Comment by Bram1903** [comment]
> ![Screenshot_1](https://github.com/Bram1903/MinecraftPlayerCrasher/assets/108226177/76e2d1f3-5856-4e04-8563-66d3be5b8097)
> 
> 
> 
> Yes, always error 
> 
> And always this [packetevents] Unable to grab ViaVersion client version for player! when stopping server

Ahh, I see you spoke with Retrooper abour this. I'll talk with him, and release a solution as soon as possible!

**Comment by Bram1903** [comment]
Hello @F3F5,

Could you give the following snapshot a try? 
https://github.com/Bram1903/AntiHealthIndicator/releases/tag/v1.1.3-SNAPSHOT

Let me know if that fixes the issue! 

Kind regards,
Bram

**Comment by F3F5** [comment]
yep

**Comment by Bram1903** [comment]
> yep

Did it fix your issue?

**Comment by F3F5** [comment]
> > yep
> 
> Did it fix your issue?

seems yes

**Comment by Bram1903** [comment]
Perfect. If the bug does occur again, please feel free to respond to this issue again!

**Comment by F3F5** [comment]
[07:17:58 INFO]: [packetevents] Unable to grab ViaVersion client version for player!

[07:17:58 INFO]: [packetevents] Unable to grab ViaVersion client version for player!

**Comment by F3F5** [comment]
@Bram1903

**Comment by Bram1903** [comment]
@F3F5 On what version if your Minecraft server running, and what is the version of your ViaVersion?

**Comment by F3F5** [comment]
> @F3F5 On what version if your Minecraft server running, and what is the version of your ViaVersion?

1.12.2 dionysus + ViaVersion 4.10.0

**Comment by Bram1903** [comment]
Ahh, I've seen a message about this in the PacketEvents Discord. The latest ViaVersion broke the way PacketEvents can grab the client version. Unfortunately, we need to wait for PacketEvents to finish their 1.20.5 update. 

I am currently updating the plugin to no longer shade PacketEvents, but rather mark it as a required dependency. In that way, I hope it becomes easier for server administrators like yourself to update PacketEvents itself rather than having to wait for a new release of mine to get the plugin working again.

**Comment by F3F5** [comment]
solution is download packetevents from github latest commit?

**Comment by Bram1903** [comment]
>  solution is download packetevents from github latest commit?  (accept friend invite michaelkozlov discord)

Well, not at the moment, but once they merge the 1.20.5 PR you should be able to get the plugin working by simply updating PacketEvents in your plugins. I just released a new version as can be found in the releases page. You can find the download link to the latest PacketEvents build in the README of this repository.

**Comment by F3F5** [comment]
![Screenshot_1](https://github.com/Bram1903/MinecraftPlayerCrasher/assets/108226177/0f46a112-2a84-405c-b4e7-cc44fe458115)

**Comment by F3F5** [comment]
protocollib better after all issues of packetevents

**Comment by Bram1903** [comment]
> protocollib better after all issues of packetevents 

This is utter nonsense. ProtocolLib doesn't even yet properly support 1.20.4 after months. It's much less performant and just overall messy. I can't even describe how much more issues would arise when using ProtocolLib instead of PE. I wrote my AntiHealtIndicator in ProtocolLib first and I had the most random and annoying bugs that were all related to ProtocolLib and that worked completely fine with almost the exact same code on PE. If you don't like PE feel free to rewrite this project yourself using ProtocolLib and use that 😁

Kind regards,
Bram
