### ISSUE TITLE
[Feature] 1.20.6 paper is out!

### ISSUE THREAD

**Issue by F3F5** [Bram1903/MinecraftPlayerCrasher#8]
https://pastebin.com/0Dy8m5Zw - 1.20.5 plugin error
We're waiting for packetevents https://github.com/retrooper/packetevents/pull/658

**Comment by Bram1903** [comment]
Paper 1.20.5 hasn't been released yet. Only a few hours ago they released their first experimental build, which is not meant for production usage. 

This plugin currently does not support 1.20.5, but once PacketEvents updates their library I will update mine as well. This issue is a bit unnecessary in my opinion, but thanks anyway.
